// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only sharing what we want)
const {john, peter} = require('./names')
const sayHI = require('./utils')
const data = require('./alternative-flavor')
console.log(data)
require('./mindgrenade')
sayHI('susan')
sayHI(john)
sayHI(peter)